
GET  https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQ1LCJlbWFpbCI6ImNhbmR5QG1hbmdvLmNvbSIsImlhdCI6MTY1MDMxODUwNH0.nPHZksaNvtny7L6BL0udVCFWE87dVti6c13X1mNppiI

#####

POST   https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MzQ1LCJlbWFpbCI6ImNhbmR5QG1hbmdvLmNvbSIsImlhdCI6MTY1MDMxODUwNH0.nPHZksaNvtny7L6BL0udVCFWE87dVti6c13X1mNppiI

{
"title": "Roberto Bananito",
"description": "Today I made banana burgers. 6/10"
}

#####
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register
Content-Type: application/json 

{
"email": "candy@mango.com",
"password": "mango"
}

#####
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json 

{
"email": "candy@mango.com",
"password": "mango"
}