
GET  https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer 
#####

POST   https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Content-Type: application/json
Authorization: Bearer 

{
"title": "Roberto Bananito",
"description": "Today I made banana burgers. 6/10"
}

#####
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register
Content-Type: application/json 

{
"email": "candy@mango.com",
"password": "mango"
}

#####
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json 

{
"email": "candy@mango.com",
"password": "mango"
}