
GET  https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJlbWFpbCI6ImRvdnplbUBtYW5nby5jb20iLCJpYXQiOjE2NTAwMTgzMDh9.7FUo2b1beFdsqmlEJqFrjek__g3L6wy10qz8ybam2E4
#####

POST   https://autumn-delicate-wilderness.glitch.me/v1/content/skills
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MjAwLCJlbWFpbCI6ImRvdnplbUBtYW5nby5jb20iLCJpYXQiOjE2NTAwMTgzMDh9.7FUo2b1beFdsqmlEJqFrjek__g3L6wy10qz8ybam2E4

{
"title": "Protein pancakes",
"description": "Thats very yummy"
}

#####
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/register
Content-Type: application/json 

{
"email": "dovzem@mango.com",
"password": "mango"
}

#####
POST https://autumn-delicate-wilderness.glitch.me/v1/auth/login
Content-Type: application/json 

{
"email": "dovzem@mango.com",
"password": "mango"
}